### ISSUE TITLE
Functions added to top-level scope on import

### ISSUE THREAD

**Issue by null-a** [JuliaStats/DataArrays.jl#141]
As I understand Julia's module system, `import DataArrays` is expected to only bring namespaced functions into scope, but that isn't the case:

```
julia> methods(sample)
ERROR: sample not defined
julia> import DataArrays
julia> methods(sample)
# 7 methods for generic function "sample":
```

This is caused by the `using StatsBase` [here](https://github.com/JuliaStats/DataArrays.jl/blob/master/src/DataArrays.jl#L1) which I tried removing, after which your tests still pass.

Is this is the intended behaviour? Would you consider a pull request to change it in order to give users more control over what is brought into scope?

**Comment by garborg** [comment]
With that change, after `using DataArrays` an unqualified definition of a name like `mode` would switch to extending `StatsBase.mode`, which wouldn't be right, either. I'd be for following the pattern used in `DataFrames.jl`:

getting rid of the first `using StatsBase`, and replacing the second with this:
```julia
using Reexport
@reexport using StatsBase
```
 (and adding `Reexport` to `REQUIRE`).

**Comment by johnmyleswhite** [comment]
+1 to Sean's proposal

**Comment by null-a** [comment]
`@reexport` sounds good. I learned something new, thanks!

Can you help me understand what you meant by:

> With that change, after using DataArrays, an unqualified definition of a name like mode would switch to extending StatsBase.mode

In that situation wouldn't `mode` be undefined,  and wouldn't defining it leave `StatsBase.mode` untouched?

For example, this is with the first `using StatsBase` removed, and I can't reconcile it with what you were describing:

```
julia> using DataArrays
julia> methods(StatsBase.mode)
# 2 methods for generic function "mode":
mode{T<:Integer}(a::AbstractArray{T<:Integer,N},rgn::UnitRange{T<:Integer})
mode{T}(a::AbstractArray{T,N})
julia> mode() = :mode
mode (generic function with 1 method)
julia> methods(mode)
# 1 method for generic function "mode":
mode() at none:1
julia> methods(StatsBase.mode)
# 2 methods for generic function "mode":
mode{T<:Integer}(a::AbstractArray{T<:Integer,N},rgn::UnitRange{T<:Integer})
mode{T}(a::AbstractArray{T,N})
```

What am I missing?

**Comment by garborg** [comment]
You're right -- I was thinking of something like `import StatsBase: modes` which isn't relevant here. Thanks for checking! I'd still use `Reexport` here to keep the behaviour of `using DataArrays` unchanged while fixing the behaviour of `import DataArrays`.

**Comment by null-a** [comment]
Thanks for explaining! Using `Reexport` to keep the existing behaviour is neat.

**Comment by garborg** [comment]
Great!
