### ISSUE TITLE
Indexing is broken

### ISSUE THREAD

**Issue by gragusa** [JuliaStats/DataArrays.jl#153]
This is reproducible (on `0.4.0-dev+5252`) (and generate problems with the indexing of DataFrames (see issue [see issue #810](https://github.com/JuliaStats/DataFrames.jl/issues/810):

```
da = @data([1, 2, NA, 4])
da[1:3]
```
```
ERROR: DimensionMismatch("index 1 has size (3,), but size(A) = ()")
 in checksize at multidimensional.jl:287
 in anonymous at /Users/gragusa/.julia/v0.4/Compat/src/ngenerate.jl:128
 in getindex at /Users/gragusa/.julia/v0.4/DataArrays/src/indexing.jl:159
```

I tracked down the issue to a misbehaviour of `Base.index_shape`

```
Base.index_shape(Base.to_index([1:2], [1])...)
```

gives

```
(1,)
```
instead of
```
(2,1)
```

**Comment by alyst** [comment]
I've also hit the issue. There's already a pull request #152 addressing this. Until it's merged to the master, you can just switch to that branch.
