### ISSUE TITLE
Needs tagging

### ISSUE THREAD

**Issue by timholy** [JuliaStats/DataArrays.jl#166]
Precompilation is causing failures in packages that depend on DataArrays; 074c5b492ce07e1e56bd4298fa48494b093d9c1e fixes it but only if someone tags a new release.

**Comment by johnmyleswhite** [comment]
Wasn't DataArrays tagged a while back? https://github.com/JuliaLang/METADATA.jl/blob/metadata-v2/DataArrays/versions/0.2.18/sha1refers to a commit after the precompilation commit

**Comment by timholy** [comment]
Yes, you are right. Tag wasn't in the repo which is why I was confused. Must have been the fault of another package. Sorry for the noise.

**Comment by johnmyleswhite** [comment]
You may have produced the least noise in Julia's history, @timholy. No apologies ever needed.
