### ISSUE TITLE
for DataArrays documentation see DataFrames

### ISSUE THREAD

**Issue by deszoeke** [JuliaStats/DataArrays.jl#177]
There is a bit more information on DataArrays on the DataFrames documentation site.
http://dataframesjl.readthedocs.org/en/latest/index.html

Since new users like me don't automatically know that DataArrays came from DataFrames, the DataArrays documentation would benefit from a link to the DataFrames documentation.

Many places (?mean and ?std) I have seen

> For applications requiring the handling of missing data, the DataArray package is recommended.

Yet nowhere have I found documentation of methods for evaluating missing-data-ignoring statistical and simple arithmetic functions (e.g. mean(), std(), sum()) using DataArrays.

From reading Base.mean code, I am experimenting with `skipna=true`. This seems to be a very stealthy (undocumented) method.

**Comment by johnmyleswhite** [comment]
We're chronically short-staffed on people who can put in time to do this sort of work, so a pull request with improved documentation would be very helpful.

**Comment by micahjsmith** [comment]
@johnmyleswhite is this still open for contribution? Not much documentation to be found. I would find the in-source docstrings very helpful.

**Comment by johnmyleswhite** [comment]
No, please contribute documentation to NullableArrays.

**Comment by nalimilan** [comment]
Especially https://github.com/JuliaStats/NullableArrays.jl/issues/160.

**Comment by ararslan** [comment]
The package now includes docstrings and documentation generated via Documenter. See the README for links to the stable and latest docs.
