### ISSUE TITLE
Type signature of setlevels! is too strict

### ISSUE THREAD

**Issue by tlnagy** [JuliaStats/DataArrays.jl#201]
This has been causing the tests on [Gadfly](https://github.com/dcjones/Gadfly.jl) master to be broken for some time

```{.julia}
julia> using RDatasets, DataFrames

julia> barley = dataset("lattice", "barley");

julia> setlevels!(barley[:Year], ["1931", "1932"])
ERROR: MethodError: `setlevels!` has no method matching setlevels!(::DataArrays.PooledDataArray{ByteString,UInt8,1}, ::Array{ASCIIString,1})
Closest candidates are:
  setlevels!{T,R}(::DataArrays.PooledDataArray{T,R,N}, ::AbstractArray{T,1})
  setlevels!{T,R}(::DataArrays.PooledDataArray{T,R,N}, ::Dict{T,T})
  setlevels!{T,R}(::DataArrays.PooledDataArray{T,R,N}, ::Dict{T,Any})

julia> setlevels!(barley[:Year], ByteString["1931", "1932"]);
```
Typing the array shouldn't be necessary

**Comment by nalimilan** [comment]
I guess we could add a function calling `convert` automatically. But the main problem here is the unfortunate situation of strings in 0.4+Compat.

Would you make a PR to fix this?

**Comment by tlnagy** [comment]
> But the main problem here is the unfortunate situation of strings in 0.4+Compat.

Do you think all the changes to strings in 0.5 will fix some these problems?

**Comment by nalimilan** [comment]
What I meant is that the existence of `ByteString`, `ASCIIString` and `UTF8String` and the type-instability depending on whether literal strings contain non-ASCII chars makes this issue quite visible on Julia 0.4. The fact that `Compat.String` is equivalent to `ByteString` there doesn't help either. In 0.5, there's only `String`, so you're much less likely to use different string types.

But in general I think that's a good change anyway.
