### ISSUE TITLE
test/sort.jl broken on current Julia master

### ISSUE THREAD

**Issue by martinholters** [JuliaStats/DataArrays.jl#208]
Since https://github.com/JuliaLang/julia/pull/17079/commits/a4e3cd29897a6853faf9f1ab0dfb657cbc521cd1, `typed_vcat` (called from `vcat`) explicitly converts its arguments to `Array`s. This breaks `isequal(sort(da), [DataArray(sort(dropna(da))); DataArray(T, nna)])` since the `[...; ...]` tries to put `NAtype`s into an `Array{Float64,1}`.

**Comment by tkelman** [comment]
If the best solution to this is to merge https://github.com/JuliaLang/julia/pull/17079 for 0.5, please let us know quickly.

**Comment by ararslan** [comment]
Someone else surely would know better than I would (maybe @andreasnoack? he knows everything) but I'm not sure what we could do in the short term on our end to accomodate that change.

**Comment by andreasnoack** [comment]
The reasoning behind https://github.com/JuliaLang/julia/pull/17079 was that `full(a)` would always be `convert(Array, a)` but that is clearly not true so the solution should either be to revert it modify it but given how close we are to 0.5, reverting might be the right choice.

**Comment by martinholters** [comment]
Actually, the fact that, for some `da::DataArray{T}`, `isa(da, AbstractArray{T})` and hence `eltype(da) == T`, but potentially `!isa(da[idx], T)` looks like it is breaking a lot of assumptions. Funny it doesn't trigger more errors.

That said, the simplest solution for this particular issue might be adding specialized methods to `vcat` (and probably the other cat methods, too).

Or, even simpler, disallow cat'ing `DataArray`s and rewrite the offending tests :smile:

**Comment by nalimilan** [comment]
This is annoying. I think this shows that DataArrays are fundamentally broken as they don't respect the element type they declare. OTOH breaking DataArrays in Julia 0.5 would be a serious issue since the replacement isn't completely ready yet. So either we're able to override all `cat` methods for DataArrays, or we should keep JuliaLang/julia#17079 reverted until 0.6.

**Comment by andreasnoack** [comment]
https://github.com/JuliaLang/julia/pull/17079/commits/a4e3cd29897a6853faf9f1ab0dfb657cbc521cd1 Has been reverted so this is not an issue anymore. I'm wondering if the element type of a `DataArray` should be `Union{T,NAType}`. That seems right to me and would work with https://github.com/JuliaLang/julia/pull/17079/commits/a4e3cd29897a6853faf9f1ab0dfb657cbc521cd1
