### ISSUE TITLE
`anyna` failure

### ISSUE THREAD

**Issue by panlanfeng** [JuliaStats/DataArrays.jl#216]
Due to [this line](https://github.com/JuliaStats/DataArrays.jl/blob/master/src/abstractdataarray.jl#L88)
we have the following unexpected result
```julia
julia> anyna(Any[NA, 1])
false
```
We should probably define it as 
```julia
anyna(a::AbstractArray) =any(isna(a))
allna(a::AbstractArray) =all(isna(a))
```

**Comment by nalimilan** [comment]
Yes, I don't think using `NA`s inside standard arrays is well supported. Feel free to open a PR to fix that. (But the development focus is on NullableArrays these days, so probably not worth spending too much time on this.)
