### ISSUE TITLE
dropna for Float64 & missing value index

### ISSUE THREAD

**Issue by genwei007** [JuliaStats/DataArrays.jl#224]
Hi DataArrays developers:

I have two naive questions but cannot found out solution:
(1)
y = @data(ones(3,3))
y[2,2] = NA
sum(dropna(y))
MethodError: no method matching dropna(::DataArrays.DataArray{Float64,2})

(2) 
how to get the index of missing values? Like `which(y, arr.ind = TRUE)` in R.

**Comment by ararslan** [comment]
1. I think `dropna` is only defined for vectors, whereas in your case you have a matrix. So you'll have to reshape it into a `DataArray{Float64,1}`.

2. I believe that's `findna`.

**Comment by genwei007** [comment]
Thanks for the quick answer. Could you give the code? I cannot achieve it in both cases, by `dropna(reshape(x,4,1))` and no `findna` function found.

**Comment by ararslan** [comment]
The following works for me:
```julia
y = @data(ones(3,3))
y[2,2] = NA
flat = vec(y)[:]
sum(dropna(flat))
```
For whatever reason, `findna` isn't exported. So you can do
```julia
using DataArrays: findna
findna(x) # returns Any[[2,2]]
```
Let me know if that works for you.

**Comment by genwei007** [comment]
Thank you! They works perfectly for me. Hope there is more complete documentation for DataArrays.

**Comment by ararslan** [comment]
Glad it works for you. This package will be deprecated soon in favor of NullableArrays (Julia 0.5) or solution in base Julia (hopefully in Julia 0.6). It is no longer being actively developed.
