### ISSUE TITLE
add label kw to cut()

### ISSUE THREAD

**Issue by floswald** [JuliaStats/DataArrays.jl#225]
```julia
df = DataFrame(a=1:5,b=rand(5))
5×2 DataFrames.DataFrame
│ Row │ a │ b         │
├─────┼───┼───────────┤
│ 1   │ 1 │ 0.18422   │
│ 2   │ 2 │ 0.675841  │
│ 3   │ 3 │ 0.858718  │
│ 4   │ 4 │ 0.0160615 │
│ 5   │ 5 │ 0.138444  │

julia> @transform(df,c=cut(:b,2))
5×3 DataFrames.DataFrame
│ Row │ a │ b         │ c                     │
├─────┼───┼───────────┼───────────────────────┤
│ 1   │ 1 │ 0.18422   │ "[0.0160615,0.18422]" │
│ 2   │ 2 │ 0.675841  │ "(0.18422,0.858718]"  │
│ 3   │ 3 │ 0.858718  │ "(0.18422,0.858718]"  │
│ 4   │ 4 │ 0.0160615 │ "[0.0160615,0.18422]" │
│ 5   │ 5 │ 0.138444  │ "[0.0160615,0.18422]" │
```

I would find it oftentimes more helpful to not have the label "[0.0160615,0.18422]", but an integer `1` for the first group, etc. could we have `cut(x::AbstractArray{T<:Any,1}, ngroups::Integer;labels=true)`?

**Comment by nalimilan** [comment]
Makes sense, but DataArrays is going to be deprecated. I guess this function should be moved to CategoricalArrays.jl since it makes sense to return an ordinal variable. Could you open an issue or (even better) file a PR there?

**Comment by nalimilan** [comment]
See https://github.com/JuliaData/CategoricalArrays.jl/pull/46.
