### ISSUE TITLE
Function isprime() not found in Julia v 0.6 1781

### ISSUE THREAD

**Issue by colbec** [JuliaStats/DataArrays.jl#226]
`isprime()` is still found in Julia v 0.5 so DataArrays still works there.
In v 0.6 `isprime()` is not found unless we `Pkg.add("Primes")`, after which `isprime()` is found (isprime has been moved out of Base).
However precompile of DataArrays 0.3.10 fails with `ERROR: LoadError: LoadError: UndefVarError: isprime not defined`

**Comment by tlnagy** [comment]
This is causing Gadfly's tests to fail on julia master.

**Comment by ararslan** [comment]
Fixed by #227.
