### ISSUE TITLE
"StatsBase.WeightVec is deprecated" warning

### ISSUE THREAD

**Issue by gmoutsin** [JuliaStats/DataArrays.jl#258]
When the package was precompiled, it produced several times the warning "StatsBase.WeightVec is deprecated, use StatsBase.Weights instead."

It was today with the version that Pkg downloaded.

**Comment by nalimilan** [comment]
See https://github.com/JuliaStats/DataArrays.jl/pull/254.

**Comment by ararslan** [comment]
Should be fixed once DataArrays 0.5.2 is available.
