### ISSUE TITLE
Inference failure/indexing issues

### ISSUE THREAD

**Issue by bramtayl** [JuliaStats/DataArrays.jl#276]
Maybe a DataFrames issue?

```julia
julia> d = DataFrame(a = [1, 2]);

julia> d[d[:a] .> 1, :]
1×1 DataFrames.DataFrame
│ Row │ a │
├─────┼───┤
│ 1   │ 2 │

julia> d[map(a -> a > 1, d[:a]), :]
ERROR: MethodError: no method matching getindex(::DataFrames.DataFrame, ::DataArrays.DataArray{Any,1}, ::Colon)
```

**Comment by bramtayl** [comment]
[Ref](https://github.com/JuliaLang/julia/issues/15276#issuecomment-316158293)

**Comment by JeffBezanson** [comment]
It looks like here: https://github.com/JuliaStats/DataArrays.jl/blob/513c046836f4e066feece28671be1c1acafa2329/src/datavector.jl#L106 `map` always returns an `Any` array.

**Comment by ararslan** [comment]
The difference is that `broadcast` is correctly inferring the element type to be a subtype of `Real` (in this case `Bool`), so it's going through [this method](https://github.com/JuliaStats/DataFrames.jl/blob/19821b9060a691646114c064e1bc0b8e290c8f66/src/dataframe/dataframe.jl#L276). For whatever reason, `map` is incorrectly inferring the element type to be `Any`, and there isn't a method for that.

**Comment by ararslan** [comment]
Ugh, why did we define it like that...

**Comment by ararslan** [comment]
Okay well I'll work on a fix.

**Comment by JeffBezanson** [comment]
I believe the default definition of `map` in Base works here:

```
julia> invoke(map, (Any,AbstractArray), x->x>1, a)
2-element DataArrays.DataArray{Bool,1}:
 false
  true
```

It uses `similar` to get a container of the same type, and iterator traits, plus the current officially-sanctioned tricks for getting the right element type. I spent a lot of time on it... :)

**Comment by bramtayl** [comment]
Should there also be a subsetting method defined for DataArrays of eltype any?

**Comment by ararslan** [comment]
no

**Comment by bramtayl** [comment]
There's also this inference failure: 

```julia
a = @data [1, 2]
broadcast(x -> x > 1, a)
broadcast(x -> x > mean(a), a)

a = [1, 2]
broadcast(x -> x > 1, a)
broadcast(x -> x > mean(a), a)
```

**Comment by bramtayl** [comment]
This infers correctly though. So I guess the compiler doesn't know mean is a pure function? Mean is indeed a pure function, right?

```julia
a = @data [1, 2]
Base.@pure mymean(x) = mean(x)
broadcast(x -> x > mymean(a), a)
```

**Comment by nalimilan** [comment]
@bramtayl I don't think purity is the right solution here. `@pure` should only be used in very specific cases. It seems that the fact that `mean(a)` has an inferred return type of `Union{NAtype, Float64}` is an issue for the compiler. Could you file a separate issue?

**Comment by bramtayl** [comment]
A dataarrays issue?

**Comment by nalimilan** [comment]
Yes.

**Comment by nalimilan** [comment]
See https://github.com/JuliaStats/DataArrays.jl/issues/282.
