### ISSUE TITLE
Systematic test coverage

### ISSUE THREAD

**Issue by johnmyleswhite** [JuliaStats/DataArrays.jl#28]
I think our current ad hoc testing practice lets too many things slip through the cracks. I propose that we switch to a simple, systematic testing rule: every file in `src` needs to have a mirror file in `test` that contains tests that check every function defined in the `src` file in the order present in the `src` file. This kind of test file is pretty boring to write, but is much more systematic and reliable. I've started going this myself, so I'll upload tests as they get constructed.

One other rule: I'd propose that the tests for the `src` file, `x.jl` go in a `test` file called `x.jl` that contains a module called `TestX`. This ensures parallelization across test files. Ideally the module would contain tests written as functions, which can be easily analyzed by a code checker to confirm systematic test coverage of the `src` file.

**Comment by ararslan** [comment]
Closing since we now have comprehensive tests and code coverage tracking
