### ISSUE TITLE
broadcast() inference issue with mean() and >

### ISSUE THREAD

**Issue by bramtayl** [JuliaStats/DataArrays.jl#282]
```julia
a = @data [1, 2]
broadcast(x -> x > 1, a)::DataArrays.DataArray{Bool,1} # OK
broadcast(x -> x > mean(a), a)::DataArrays.DataArray{Any,1} # Not OK
```

But:
```julia
a = [1, 2]
broadcast(x -> x > 1, a)::BitArray{1} #OK
broadcast(x -> x > mean(a), a)::BitArray{1} # OK
```

**Comment by nalimilan** [comment]
It seems that the fact that `mean(a)` has an inferred return type of `Union{NAtype, Float64}` confuses inference.

**Comment by bramtayl** [comment]
I still think this is a purity issue. Quoting Stefan:

> Just to clarify: having a value in a box in the inner function doesn't mean that it's type couldn't be inferred – that's a completely orthogonal issue – it means that the compiler couldn't prove that the value wouldn't change during the lifetime of the inner function.

But of course, this is not the case: the mean of a will not change over the course of broadcasting.

**Comment by nalimilan** [comment]
I don't understand what boxes have to do with this issue. Whether `mean` changes between iterations or not should be irrelevant to choose the return type: what matters is that the type remains the same. And indeed adding a type assertion manually fixes the problem:
```julia
julia> broadcast(x -> x > mean(a)::Float64, a)
2-element DataArrays.DataArray{Bool,1}:
 false
  true
```

**Comment by nalimilan** [comment]
The issue does not appear with standard `Array` only because its `broadcast` method computes the element type based on the actual return values when inference does not give a concrete type. To fix that problem for `DataArray`, we would need to implement the same approach. I'm not sure it's worth spending time on this since moving to `Array{T, Null}` will fix it.

**Comment by bramtayl** [comment]
Oh, ok, maybe I was just confused then
