### ISSUE TITLE
PooledDataArray depreciated?

### ISSUE THREAD

**Issue by Ken-B** [JuliaStats/DataArrays.jl#298]
I'm looking into porting `FixedEffectModels` over to the new `DataFrames` v0.11. It heavily uses `PooledDataVector`, which I read in the Readme here is depreciated in favour of CategoricalArrays.

However, looking at the code here, it seems `PooledDataVector` is still very much present and not depreciated. Am I missing something (pun intended)? So, my main question, should I port over `FixedEffectModels` to use `CategoricalArrays`?

Thanks

**Comment by nalimilan** [comment]
`PooledDataVector` is just an alias for `PooledDataArray{T, 1}`, so it's also deprecated. Indeed the way forward is `CategoricalArray`. Feel free to ask for help on the #data Slack channel!
