### ISSUE TITLE
rewrite and rename percent_change() -> percentchange() 

### ISSUE THREAD

**Issue by milktrader** [JuliaStats/DataArrays.jl#36]
This method is very common and when it comes to naming it, it's easy to start calling it something different depending on what package you happen to be using. R has this issue and calls this method `ROC`, `Delt`, `delt`, `returns` and probably a handful of other names. TimeSeries uses `percentchange` now (I just deprecated simple_return and log_return).  That naming is consistent with Julian convention to remove underscores, the bane of Ruby variable names. 

`percentchange.TimeSeries` also offers a kwarg for either simple percent change (which is what the currently implemented `percent_change` offers), and log percent change. 

I can do a PR on this. It will also require 3 changes to files in DataFrames, where the method is referenced as `percent_change`. 

Here is what the code looks like:

``` julia
function percentchange(dv::DataArray; method="simple")
  if method == "simple" 
    return expm1(log_return(dv))
  elseif method == "log" 
    return log_return(dv)
  else 
    throw("only simple and log methods supported")
  end
end

function log_return(dv::DataArray)
  pad(diff(log(dv)), 1, 0, NA)
end
```

The code is short enough where you can refactor and put the definition of log_return inside the original method.

**Comment by ararslan** [comment]
The function has been deprecated
